# Site settings
title: Greece Competition
# client:
#   name: Client Name
#   link: "#client-name"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Experience the calm and tranquillity offered by this little piece of island paradise. A luxurious and opulent resort on the largest island in Greece, you'll have plenty to do should you wish to explore beyond the hotel, but we wouldn't blame you if you wanted to stay in this sanctuary and soak-up the 5-star service.

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/greece-competition" # the subpath of your site, e.g. /blog/
img:     "/greece-competition/_assets/img"
css:     "/greece-competition/_assets/css"
js:      "/greece-competition/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed